# Generated by Django 5.1.7 on 2025-06-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
