# Generated by Django 5.1.7 on 2025-06-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeemodel_created_at_employeemodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeemodel',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
