# Generated by Django 5.1.7 on 2025-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employeemodel_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
