# Generated by Django 5.1.7 on 2025-06-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
