# Generated by Django 5.1.7 on 2025-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_taskmodel_deleted_at_taskmodel_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='taskmodel',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
