# Generated by Django 5.1.7 on 2025-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_taskmodel_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
